# Generated by Django 4.0.3 on 2022-04-08 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_evento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='data_de_nascimento',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='telefone_celular',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='telefone_fixo',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='usuario',
        ),
        migrations.AddField(
            model_name='evento',
            name='cep',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='evento',
            name='cidade',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='evento',
            name='dataEHoraDeInicio',
            field=models.DateTimeField(default=None, null=True, verbose_name='Data e hora de início'),
        ),
        migrations.AddField(
            model_name='evento',
            name='endereco',
            field=models.CharField(max_length=50, null=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='evento',
            name='eventoPrincipal',
            field=models.TextField(null=True, verbose_name='Evento Principal'),
        ),
        migrations.AddField(
            model_name='evento',
            name='logotipo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Logotipo'),
        ),
        migrations.AddField(
            model_name='evento',
            name='palavrasChave',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Palavras chave'),
        ),
        migrations.AddField(
            model_name='evento',
            name='realizador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.pessoa'),
        ),
        migrations.AddField(
            model_name='evento',
            name='sigla',
            field=models.CharField(max_length=10, null=True, verbose_name='Sigla'),
        ),
        migrations.AddField(
            model_name='evento',
            name='uf',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='nome',
            field=models.CharField(max_length=50, null=True, verbose_name='Nome'),
        ),
    ]
