# Generated by Django 4.0.3 on 2022-04-08 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_pessoa_data_de_nascimento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoCientifico',
            fields=[
                ('evento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.evento')),
                ('issn', models.CharField(max_length=15, verbose_name='ISSN')),
            ],
            bases=('app.evento',),
        ),
    ]
