# Generated by Django 4.0.3 on 2022-04-09 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_artigocientifico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigocientifico',
            name='autores',
            field=models.ManyToManyField(to='app.pessoa'),
        ),
        migrations.AlterField(
            model_name='artigocientifico',
            name='evento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.eventocientifico'),
        ),
    ]
