# Generated by Django 4.0.3 on 2022-04-09 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_artigocientifico_autores_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artigocientifico',
            name='autores',
        ),
        migrations.RemoveField(
            model_name='artigocientifico',
            name='evento',
        ),
        migrations.RemoveField(
            model_name='artigocientifico',
            name='titulo',
        ),
    ]
