# Generated by Django 4.0.3 on 2022-04-09 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_artigocientifico_autores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigocientifico',
            name='titulo',
            field=models.CharField(max_length=128, null=True, verbose_name='Título'),
        ),
    ]
