# Generated by Django 4.0.3 on 2022-04-09 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_artigocientifico_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigocientifico',
            name='autores',
            field=models.ManyToManyField(to='app.pessoa'),
        ),
    ]
