# Generated by Django 4.0.3 on 2022-04-09 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_artigocientifico_autores'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigocientifico',
            name='evento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.eventocientifico'),
        ),
    ]
