# Generated by Django 4.0.3 on 2022-04-18 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_artigocientifico_evento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.pessoa')),
                ('curriculo', models.CharField(max_length=128, verbose_name='Currículo')),
                ('artigos', models.ManyToManyField(to='app.artigocientifico')),
            ],
            bases=('app.pessoa',),
        ),
    ]
