# Generated by Django 4.0.3 on 2022-04-18 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_autor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PessoaJuridica',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.pessoa')),
                ('cnpj', models.CharField(max_length=100, verbose_name='CNPJ')),
                ('razaoSocial', models.CharField(max_length=250, verbose_name='Razão Social')),
            ],
            bases=('app.pessoa',),
        ),
    ]
