# Generated by Django 4.0.3 on 2022-04-18 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_pessoafisica_alter_pessoajuridica_cnpj_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='artigos',
        ),
        migrations.AlterField(
            model_name='artigocientifico',
            name='autores',
            field=models.ManyToManyField(to='app.autor'),
        ),
        migrations.AlterField(
            model_name='pessoafisica',
            name='cpf',
            field=models.CharField(max_length=20, verbose_name='CPF'),
        ),
    ]
