# Generated by Django 4.0.3 on 2022-04-18 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_autor_artigos_alter_artigocientifico_autores_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artigocientifico',
            name='titulo',
        ),
    ]
