# Generated by Django 4.0.3 on 2022-04-18 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_artigocientifico_titulo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArtigoCientifico',
        ),
    ]
