# Generated by Django 4.0.3 on 2022-04-18 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_delete_artigocientifico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='curriculo',
            field=models.CharField(max_length=128, null=True, verbose_name='Currículo'),
        ),
        migrations.CreateModel(
            name='ArtigoCientifico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=128, null=True, verbose_name='Título')),
                ('autores', models.ManyToManyField(to='app.autor')),
                ('evento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.eventocientifico')),
            ],
        ),
    ]
